#Inspiration for OSX from: https://github.com/bjones1/CodeChat/blob/master/.travis.yml
os: linux
language: python
python:
  - 3.6
env:
  global:
  - GETH_URL_LINUX='https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.13-225171a4.tar.gz'
  - GETH_URL_MACOS='https://gethstore.blob.core.windows.net/builds/geth-darwin-amd64-1.8.13-225171a4.tar.gz'
  - GETH_VERSION='1.8.13'


matrix:
  include:
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=3.6 VENV=venv
  - os: linux
    language: python
    python: '3.6'

cache:
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/.rotkehlchen-test-dir
    - $HOME/.ethash
    - $HOME/.bin

before_install:
  - openssl version
  - mkdir -p $HOME/.bin
  - export PATH=$PATH:$HOME/.bin
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.travis/before_install.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo ./.travis/before_install.sh; fi
  # This needs to be outside of the before_install.sh script or else the environment
  # is not set properly for OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/travis_tools.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then get_python_environment $INSTALL_TYPE $VERSION $VENV; fi
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      export DISPLAY=:99.0;
      Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

install:
  - python -m pip install -U pip
  - pip install -U pip wheel coveralls "coverage<4.4"
  - pip install pytest-travis-fold
  - pip install flake8
  - pip install -r requirements.txt

# Run the tests.
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/test_tools.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -m pytest rotkehlchen; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then coverage run --source rotkehlchen/ -m pytest --travis-fold=always $TEST_TYPE; fi
  - npm config set python python2.7
  # If we add the specific electron runtime compile in OSX fails with an error
  # that looks like this: https://www.npmjs.com/package/nan#compiling-against-nodejs-012-on-osx
  # - npm install --runtime=electron --target=1.8.4
  - npm install
  - PYTHON=/usr/bin/python2.7 ./node_modules/.bin/electron-rebuild
  - npm test

before_deploy:
  - ./package.sh

deploy:
  - provider: releases
    api_key:
      secure: HaRYa6DxLldQJALMBGjbFo1A/c5343mUHbYE+BS5/x/yNwLw7A2dwrGbyKEyLwm01YB3l0RTQwldF0bavhJzpzbJuqhO1IoHFwFgBHczi7dBTKgaRzOIZsEEuCf5+niYcUJl5NRKpYBX36NV3v7II5d986+hjthmq0jU1zXby+tisEBCPefaWXSRbGZCz6Ph0RYitq5ahaFkc3rY3TXl6/P2Ch8ApztayQFLtmA/3Ajar34/lWhcMmWUMD33A8P+UjLZxDbUs1UAq5TA6Zaw8iXcd+Tmu59cpRf/uRkI7i9OuwClnukJ+ztfzvAqgtLmFIvwgA2dkkU9Ao7Qsa8THUMgtFfe7F+5euGeoraNNG0abwVDwZomX3ZfZmKT0yU5G7z4vszSkZUx+VRWO2Br8ilnAmFd8dm/d+Nmwt96q2VpnTVL5a1SEWeyGzOyL4tBe+b7e3K6XqG2ae6fg2RkKPOusoeHDezkkrCXPY9JqikAfKAH0r4+FzW3dZLps/4onJNlaAm0gGDL7Msqw0zOZnOAoWepOGmpDfAG/Hhpq0YTOEtdVCfKAE5oDRLkPoDJt5eYevrgS4Bf4/UapTTzfjfYbnydQvsMH7CeRRgxcxFGFyber5Nm0b18KQjD5JhFH3Nf067GDMxRJe5EMPH/JxBV/1vqWttVZpfoMvgsGy4=
    file: rotkehlchen-linux-x64.zip
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
      repo: rotkehlchenio/rotkehlchen
      branch: master
  - provider: releases
    api_key:
      secure: HaRYa6DxLldQJALMBGjbFo1A/c5343mUHbYE+BS5/x/yNwLw7A2dwrGbyKEyLwm01YB3l0RTQwldF0bavhJzpzbJuqhO1IoHFwFgBHczi7dBTKgaRzOIZsEEuCf5+niYcUJl5NRKpYBX36NV3v7II5d986+hjthmq0jU1zXby+tisEBCPefaWXSRbGZCz6Ph0RYitq5ahaFkc3rY3TXl6/P2Ch8ApztayQFLtmA/3Ajar34/lWhcMmWUMD33A8P+UjLZxDbUs1UAq5TA6Zaw8iXcd+Tmu59cpRf/uRkI7i9OuwClnukJ+ztfzvAqgtLmFIvwgA2dkkU9Ao7Qsa8THUMgtFfe7F+5euGeoraNNG0abwVDwZomX3ZfZmKT0yU5G7z4vszSkZUx+VRWO2Br8ilnAmFd8dm/d+Nmwt96q2VpnTVL5a1SEWeyGzOyL4tBe+b7e3K6XqG2ae6fg2RkKPOusoeHDezkkrCXPY9JqikAfKAH0r4+FzW3dZLps/4onJNlaAm0gGDL7Msqw0zOZnOAoWepOGmpDfAG/Hhpq0YTOEtdVCfKAE5oDRLkPoDJt5eYevrgS4Bf4/UapTTzfjfYbnydQvsMH7CeRRgxcxFGFyber5Nm0b18KQjD5JhFH3Nf067GDMxRJe5EMPH/JxBV/1vqWttVZpfoMvgsGy4=
    file: rotkehlchen-darwin-x64.zip
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = osx
      repo: rotkehlchenio/rotkehlchen
      branch: master


