name: SQLDiff

on:
  pull_request_target:
    branches:
      - develop
      - bugfixes
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  sql-diff:
    name: SQLDiff
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install required
        run: sudo apt-get install -y sqlcipher sqlite3-tools

      - name: SQLDiff action
        id: sql-diff
        uses: rotki/action-sqldiff@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          files: '*.db'
